# Conclusion
Through our exploration, we identified several key takeaways about NYC's job market. In terms of job positions, the Department of Environmental Protection, Bronx District Attorney, Department of Health/Mental Hygiene, and HRA/Dept of Social Services emerged as the top four agencies with the highest number of job postings, so monitoring heated social trends is important as it tells us the city's workforce priorities. Moreover, slightly higher percentage of the position require programming languages, having some knowledge in programming language might give people more options. Regarding salaries, we found a clear association between higher career levels and increased earnings. Additionally, jobs in categories that requiring technical skills, such as Technology, Data & Innovation, had the highest median salaries, showing the importance of programming languages and other technical competencies. Thus, for those still undecided but try to make some money, learning technical skills and targeting fields like technology or engineering could open pathways to higher-paying jobs. For individuals with a specific career goal, they can benefit from using our interactive visualizations to explore job availability and salary trends within their desired field and career level.

However, our analysis is limited by the scope of the data, which includes only job postings from NYC, primarily within a one-year time frame. Expanding the dataset to include data from previous years and other states could provide a more comprehensive understanding of the job market and salary trends. Looking ahead, collecting a broader range of data in terms of both geography and time will allow us to better learn job market patterns and trends.

